# Generated by Django 4.0.4 on 2022-05-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_tags_post_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_status',
            field=models.BooleanField(default=True),
        ),
    ]
