# Generated by Django 4.0.4 on 2022-06-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birthdate',
        ),
    ]
